# Generated by Django 4.1.3 on 2022-11-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('favourite_accessories', models.ManyToManyField(blank=True, null=True, to='demo_project.accessories')),
                ('favourite_cars', models.ManyToManyField(blank=True, null=True, to='demo_project.cars')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
