# Generated by Django 4.1.3 on 2022-11-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0002_profiles_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='favourite_accessories',
            field=models.ManyToManyField(blank=True, to='demo_project.accessories'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='favourite_cars',
            field=models.ManyToManyField(blank=True, to='demo_project.cars'),
        ),
    ]
