# Generated by Django 4.1.3 on 2022-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0003_alter_profiles_favourite_accessories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
