# Generated by Django 4.1.3 on 2022-11-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0004_profiles_logged'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
