# Generated by Django 4.1.3 on 2022-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_project', '0006_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
